chat/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from chat.api.views import MessageViewSet

app_name = 'chat_api'

router = DefaultRouter()
router.register(r'messages', MessageViewSet)

urlpatterns = [
    path('chat/', include(router.urls)),
]

chat/urls.py
from django.urls import path
from chat.views import ThreadMessageList, LoginView

app_name = 'chat'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('<slug:recipient>/', ThreadMessageList.as_view(), name='thread'),
]

task2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('api/', include('chat.api.urls')),
]

chat/models.py
from django.db import models
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


class User(models.Model):
    username = models.CharField(max_length=100, unique=True, null=False, blank=False)

    def __str__(self):
        return self.username


class Thread(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='threads')
    opponent = models.ForeignKey(User, on_delete=models.CASCADE)


class Message(models.Model):
    text = models.TextField(null=False)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)

    def send(self):
        room_group_name = 'thread_%s' % self.thread.pk
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            room_group_name,
            {
                'type': 'chat_message',
                "message": self.text,
                "sender": self.sender.username,
            }
        )

    def __str__(self):
        return "message from {}".format(self.sender)

chat/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)

chat/api/views.py
from rest_framework import viewsets, mixins
from chat.models import Message
from chat.api.serializers import MessageSerializer


class MessageViewSet(mixins.ListModelMixin,
                     mixins.CreateModelMixin,
                     viewsets.GenericViewSet):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer

chat/views.py
from django.views.generic import ListView, FormView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist


from chat.models import Message, Thread, User
from chat.forms import UserForm


class ThreadMessageList(ListView):
    template_name = 'chat/thread.html'

    def __init__(self):
        super().__init__()
        self.sender = None
        self.recipient = None

    def dispatch(self, request, *args, **kwargs):
        username = request.session.get('username', None)
        try:
            self.sender = User.objects.get(username=username)
        except ObjectDoesNotExist:
            return redirect(reverse_lazy('chat:login'))

        self.recipient, created = User.objects.get_or_create(username=self.kwargs['recipient'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['sender'] = self.sender
        ctx['recipient'] = self.recipient
        return ctx

    def get_queryset(self):
        threads = Thread.objects.filter(Q(owner=self.sender) | Q(opponent=self.sender))
        if threads.exists():
            thread = threads.first()
        else:
            thread = Thread.objects.create(
                owner=self.sender,
                opponent=self.recipient,
            )
        return Message.objects.filter(thread=thread)


class LoginView(FormView):
    form_class = UserForm
    template_name = 'chat/login.html'

    def form_valid(self, form):
        request = self.request
        user, created = User.objects.get_or_create(username=form.cleaned_data['username'])
        request.session['username'] = user.username

        return HttpResponse("You can open a chat by opening chat/username")

chat/templates/chat/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Login</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
      </form>
    </body>
</html>

chat/templates/chat/thread.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20" disabled></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    <script>
        const chatMessages = [
            {% spaceless %}
            {% for message in message_list %}
                {% autoescape off %}
                    "{{ message.sender }}: {{ message.text }}",
                {% endautoescape %}
            {% endfor %}
            {% endspaceless %}
        ];
        for (var i = 0; i < chatMessages.length; i++) {
            document.querySelector('#chat-log').value += (chatMessages[i] + '\n');
        }

        const sender = '{{ sender.username }}';
        const recipient = '{{ recipient.username }}';

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + sender
            + '/'
            + recipient
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'sender': sender,
                'recipient': recipient
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>